'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {BookOpen,Plus,ArrowLeft,Send,Settings2,MoreHorizontal,Copy,Trash2,Pencil,GitBranch,RefreshCcw,Brain,ChartNoAxesColumn,ChevronRight,LogOut,X,Save,Menu,MessageCircle,UserRound,PanelLeftClose} from 'lucide-react';
import {db} from '@/lib/rp/db';
import {Character,Persona,Session,Message,Memory,Usage,models,money} from '@/lib/rp/types';
import type {User} from '@supabase/supabase-js';
type View='library'|'detail'|'chat'|'personas'|'usage';
const blankCharacter={name:'',description:'',personality:'',speech:'',world:'',secrets:'',opening:'',scenario:''};
const labels:Record<keyof typeof blankCharacter,string>={name:'이름',description:'한 줄 소개',personality:'성격',speech:'말투',world:'세계관',secrets:'비밀 설정',opening:'첫 메시지',scenario:'시작 상황'};
const accountEmail='eptm0498+rp@gmail.com';
export default function Home(){
 const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[authMode,setAuthMode]=useState<'register'|'login'|'verify'>('register'),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState('');
 const [characters,setCharacters]=useState<Character[]>([]),[personas,setPersonas]=useState<Persona[]>([]),[sessions,setSessions]=useState<Session[]>([]),[messages,setMessages]=useState<Message[]>([]),[memories,setMemories]=useState<Memory[]>([]),[usages,setUsages]=useState<Usage[]>([]);
 const [view,setView]=useState<View>('library'),[character,setCharacter]=useState<Character|null>(null),[session,setSession]=useState<Session|null>(null);
 const [editor,setEditor]=useState<Partial<Character>|null>(null),[personaEditor,setPersonaEditor]=useState<Partial<Persona>|null>(null);
 const [drawer,setDrawer]=useState<'settings'|'memory'|'history'|null>(null),[draft,setDraft]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[menuId,setMenuId]=useState<string|null>(null),[editMessage,setEditMessage]=useState<Message|null>(null),[memoryDraft,setMemoryDraft]=useState(''),[memoryEditId,setMemoryEditId]=useState<string|null>(null);
 const bottom=useRef<HTMLDivElement>(null);
 const load=useCallback(async()=>{const [c,p,s,u]=await Promise.all([db.from('rp_characters').select('*').order('created_at',{ascending:false}),db.from('rp_personas').select('*').order('created_at'),db.from('rp_sessions').select('*').order('updated_at',{ascending:false}),db.from('rp_usage').select('*').order('created_at',{ascending:false})]);if(c.error)setError(c.error.message);setCharacters(c.data||[]);setPersonas(p.data||[]);setSessions(s.data||[]);setUsages(u.data||[])},[]);
 useEffect(()=>{db.auth.getUser().then(({data})=>{setUser(data.user?.email===accountEmail?data.user:null);setReady(true)});const {data:{subscription}}=db.auth.onAuthStateChange((_event,s)=>setUser(s?.user?.email===accountEmail?s.user:null));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(user)load()},[user,load]);
 const openSession=useCallback(async(s:Session)=>{setSession(s);setCharacter(characters.find(c=>c.id===s.character_id)||null);setView('chat');setDrawer(null);const [m,r]=await Promise.all([db.from('rp_messages').select('*').eq('session_id',s.id).order('ordinal'),db.from('rp_memories').select('*').eq('session_id',s.id).order('created_at')]);setMessages(m.data||[]);setMemories(r.data||[]);setError(m.error?.message||'')},[characters]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'})},[messages,view]);
 async function login(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);const {data,error}=await db.auth.signInWithPassword({email:accountEmail,password});setBusy(false);setPassword('');if(error||!data.user||data.user.user_metadata?.rp_username!==username.trim()){if(data.user)await db.auth.signOut();setError('아이디 또는 비밀번호를 확인해 줘.')}else setUser(data.user)}
 async function register(e:React.FormEvent){e.preventDefault();setError('');const id=username.trim();if(!/^[A-Za-z0-9_가-힣]{3,24}$/.test(id))return setError('아이디는 한글·영문·숫자·밑줄로 3~24자 입력해 줘.');if(password.length<8)return setError('비밀번호는 8자 이상으로 만들어 줘.');if(password!==confirmPassword)return setError('비밀번호가 서로 달라.');setBusy(true);const {data,error}=await db.auth.signUp({email:accountEmail,password,options:{data:{rp_username:id},emailRedirectTo:'https://haeon-relay.vercel.app/rp-studio'}});setBusy(false);setPassword('');setConfirmPassword('');if(error)return setError(error.message);if(data.session&&data.user?.email===accountEmail){setUser(data.user);return}setAuthMode('verify')}
 async function saveCharacter(){if(!editor?.name?.trim())return setError('캐릭터 이름을 입력해 줘.');setBusy(true);const payload=Object.fromEntries(Object.keys(blankCharacter).map(k=>[k,k==='name'?editor.name!.trim():editor[k as keyof typeof blankCharacter]||''])) as typeof blankCharacter;const {error}=editor.id?await db.from('rp_characters').update(payload).eq('id',editor.id):await db.from('rp_characters').insert(payload);setBusy(false);if(error)return setError(error.message);setEditor(null);setError('');await load();if(character && editor.id && character.id===editor.id)setCharacter({...character,...payload})}
 async function savePersona(){if(!personaEditor?.name?.trim())return setError('페르소나 이름을 입력해 줘.');const payload={name:personaEditor.name.trim(),description:personaEditor.description||''};const {error}=personaEditor.id?await db.from('rp_personas').update(payload).eq('id',personaEditor.id):await db.from('rp_personas').insert(payload);if(error)return setError(error.message);setPersonaEditor(null);setError('');await load()}
 async function removeCharacter(c:Character){if(!confirm(`${c.name}와 모든 채팅을 삭제할까?`))return;const {error}=await db.from('rp_characters').delete().eq('id',c.id);if(error)return setError(error.message);setView('library');setCharacter(null);await load()}
 async function cloneCharacter(c:Character){const {name,description,personality,speech,world,secrets,opening,scenario}=c;const {error}=await db.from('rp_characters').insert({name:`${name} 복제`,description,personality,speech,world,secrets,opening,scenario});if(error)setError(error.message);else await load()}
 async function createSession(c:Character,personaId:string|null=null){setBusy(true);const {data,error}=await db.from('rp_sessions').insert({character_id:c.id,persona_id:personaId,title:c.name}).select().single();setBusy(false);if(error)return setError(error.message);await load();await openSession(data)}
 async function deleteSession(s:Session){if(!confirm('이 채팅을 삭제할까? 되돌릴 수 없어.'))return;const {error}=await db.from('rp_sessions').delete().eq('id',s.id);if(error)return setError(error.message);setSession(null);setMessages([]);setView('detail');await load()}
 async function changeSession(patch:Partial<Session>){if(!session)return;const {error}=await db.from('rp_sessions').update(patch).eq('id',session.id);if(error)return setError(error.message);setSession({...session,...patch})}
 async function respond(regenerate=false){if(!session||busy)return;const text=draft.trim();if(!regenerate&&!text)return;setBusy(true);setError('');try{
  if(!regenerate){const is_ooc=/^\(\(.*\)\)$|^\/ooc\s/i.test(text);const {data,error}=await db.from('rp_messages').insert({session_id:session.id,role:'user',content:text,is_ooc}).select().single();if(error)throw error;setMessages(old=>[...old,data]);setDraft('');}
  const {data:{session:auth}}=await db.auth.getSession();const r=await fetch('/api/rp-chat',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${auth?.access_token||''}`},body:JSON.stringify({sessionId:session.id,regenerate})});const result=await r.json();if(!r.ok)throw new Error(result.error||'응답에 실패했어.');
  setMessages(old=>regenerate&&old.at(-1)?.role==='model'?[...old.slice(0,-1),result.message]:[...old,result.message]);setSession(old=>old?{...old,summary:result.summary}:old);const {data:updatedMemories}=await db.from('rp_memories').select('*').eq('session_id',session.id).order('created_at');setMemories(updatedMemories||[]);await load();
 }catch(e){setError(e instanceof Error?e.message:'요청 중 오류가 났어.')}finally{setBusy(false)}}
 async function branchAt(index:number,replacement?:string){if(!session||!character)return;setBusy(true);try{const source=messages.slice(0,index+1).map((m,i)=>({role:m.role,content:i===index&&replacement!==undefined?replacement:m.content,is_ooc:m.is_ooc,model:m.model}));const {data:s,error}=await db.from('rp_sessions').insert({character_id:session.character_id,persona_id:session.persona_id,title:`${session.title} · 분기`,model:session.model,thinking:session.thinking,length:session.length}).select().single();if(error)throw error;const {error:me}=await db.from('rp_messages').insert(source.map(m=>({...m,session_id:s.id})));if(me)throw me;const {error:memError}=await db.from('rp_memories').insert(memories.map(m=>({session_id:s.id,content:m.content})));if(memError)throw memError;setEditMessage(null);await load();await openSession(s)}catch(e){setError(e instanceof Error?e.message:'분기를 만들지 못했어.')}finally{setBusy(false)}}
 async function saveMemory(){if(!session||!memoryDraft.trim())return;const q=memoryEditId?db.from('rp_memories').update({content:memoryDraft.trim()}).eq('id',memoryEditId):db.from('rp_memories').insert({session_id:session.id,content:memoryDraft.trim()});const {error}=await q;if(error)return setError(error.message);setMemoryDraft('');setMemoryEditId(null);const {data}=await db.from('rp_memories').select('*').eq('session_id',session.id).order('created_at');setMemories(data||[])}
 async function removeMemory(id:string){await db.from('rp_memories').delete().eq('id',id);setMemories(old=>old.filter(m=>m.id!==id))}
 const selectedSessions=sessions.filter(s=>s.character_id===character?.id);const sessionCost=usages.filter(u=>u.session_id===session?.id).reduce((a,u)=>a+Number(u.cost_usd),0);const characterCost=(id:string)=>usages.filter(u=>u.character_id===id).reduce((a,u)=>a+Number(u.cost_usd),0);
 const month=new Date().toISOString().slice(0,7);const monthly=usages.filter(u=>u.created_at.slice(0,7)===month);const monthCost=monthly.reduce((a,u)=>a+Number(u.cost_usd),0);
 if(!ready)return <main className="rp-root center">서재를 여는 중…</main>;
 if(!user)return <main className="rp-root login"><div className="login-card"><div className="book-mark"><BookOpen size={30}/></div><span className="eyebrow">PRIVATE STORY SPACE</span><h1>나만의 서재</h1><p>{authMode==='register'?'이 앱에서 사용할 아이디와 비밀번호를 직접 만들어.':authMode==='verify'?'가입 확인 메일을 보냈어. 메일의 링크를 누른 뒤 돌아와 로그인해.':'만들어 둔 아이디와 비밀번호로 들어와.'}</p>{authMode==='verify'?<button className="primary" onClick={()=>{setAuthMode('login');setError('')}}>확인했어 · 로그인하기</button>:<form onSubmit={authMode==='register'?register:login}><label>아이디<input autoComplete="username" value={username} onChange={e=>setUsername(e.target.value)} required minLength={3} maxLength={24}/></label><label>비밀번호<input type="password" autoComplete={authMode==='register'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)} required minLength={authMode==='register'?8:undefined}/></label>{authMode==='register'&&<label>비밀번호 확인<input type="password" autoComplete="new-password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required minLength={8}/></label>}<button className="primary" disabled={busy}>{busy?'처리 중…':authMode==='register'?'내 계정 만들기':'서재 입장하기'}</button></form>}<button className="text-button auth-switch" onClick={()=>{setAuthMode(authMode==='login'?'register':'login');setPassword('');setConfirmPassword('');setError('')}}>{authMode==='login'?'처음이야 · 계정 만들기':'이미 만들었어 · 로그인'}</button>{authMode==='register'&&<p className="auth-note">처음 한 번만 본인 확인 메일을 받아. 평소에는 아이디와 비밀번호만 쓰면 돼.</p>}{error&&<div className="error">{error}</div>}</div></main>;
 return <div className="rp-root shell"><aside className="sidebar"><div className="brand"><BookOpen size={20}/><b>서재</b><span>나만의 이야기</span></div><button className={view==='library'?'nav active':'nav'} onClick={()=>{setView('library');setDrawer(null)}}><BookOpen size={18}/> 캐릭터</button><button className={view==='personas'?'nav active':'nav'} onClick={()=>setView('personas')}><UserRound size={18}/> 내 페르소나</button><button className={view==='usage'?'nav active':'nav'} onClick={()=>setView('usage')}><ChartNoAxesColumn size={18}/> 사용 비용</button><div className="sidebar-bottom"><span>{user.email}</span><button onClick={()=>db.auth.signOut()} title="로그아웃"><LogOut size={18}/></button></div></aside>
 <main className="main">
 {view==='library'&&<><header className="page-head"><div><span className="eyebrow">MY CHARACTERS</span><h1>어떤 이야기를 시작할까?</h1><p>설정을 쌓고, 원하는 순간에 새 이야기를 열어.</p></div><button className="primary" onClick={()=>setEditor(blankCharacter)}><Plus size={18}/> 캐릭터 만들기</button></header><div className="character-grid">{characters.map((c,i)=><article className="char-card" key={c.id} onClick={()=>{setCharacter(c);setView('detail')}}><div className={'avatar tone-'+i%5}>{c.name.slice(0,1)}</div><div className="card-text"><h2>{c.name}</h2><p>{c.description||c.world||'아직 소개가 없어'}</p><span>{sessions.filter(s=>s.character_id===c.id).length}개의 이야기 <span className="dot">·</span> {money(characterCost(c.id))}</span></div><ChevronRight size={18}/></article>)}{!characters.length&&<div className="empty"><BookOpen size={35}/><h2>첫 캐릭터를 만들어 봐</h2><p>세계관과 첫 장면을 정하면 이야기를 바로 시작할 수 있어.</p><button className="primary" onClick={()=>setEditor(blankCharacter)}>캐릭터 만들기</button></div>}</div></>}
 {view==='detail'&&character&&<><header className="detail-head"><button className="icon" onClick={()=>setView('library')}><ArrowLeft/></button><div className="detail-avatar">{character.name.slice(0,1)}</div><div className="grow"><span className="eyebrow">CHARACTER</span><h1>{character.name}</h1><p>{character.description||'새 이야기를 기다리고 있어'}</p></div><button className="icon" onClick={()=>setMenuId(menuId==='character'?null:'character')}><MoreHorizontal/></button>{menuId==='character'&&<div className="pop detail-menu"><button onClick={()=>{setEditor(character);setMenuId(null)}}><Pencil size={16}/> 설정 수정</button><button onClick={()=>{cloneCharacter(character);setMenuId(null)}}><Copy size={16}/> 복제</button><button className="danger" onClick={()=>{removeCharacter(character);setMenuId(null)}}><Trash2 size={16}/> 삭제</button></div>}</header><section className="detail-summary"><span className="eyebrow">THE STORY</span><p>{character.scenario||character.world||character.personality||'시작 상황을 설정하면 여기에 표시돼.'}</p><div className="detail-facts"><span>말투 <b>{character.speech?character.speech.slice(0,48):'자유롭게'}</b></span><span>사용 비용 <b>{money(characterCost(character.id))}</b></span></div></section><div className="section-head"><h2>이야기 목록</h2><button className="primary" onClick={()=>createSession(character)}><Plus size={17}/> 새 채팅</button></div>{selectedSessions.length?<div className="session-list">{selectedSessions.map(s=><div className="session-row" key={s.id}><button className="session-open" onClick={()=>openSession(s)}><MessageCircle size={19}/><span><b>{s.title}</b><small>{s.model} · {new Date(s.updated_at).toLocaleDateString('ko-KR')}</small></span><ChevronRight size={16}/></button><button className="icon danger" onClick={()=>deleteSession(s)} aria-label="대화 삭제"><Trash2 size={17}/></button></div>)}</div>:<div className="empty compact">아직 시작한 채팅이 없어. 첫 장면을 열어 봐.</div>}</>}
 {view==='personas'&&<><header className="page-head"><div><span className="eyebrow">YOUR ROLE</span><h1>내 페르소나</h1><p>이야기마다 다른 나로 들어갈 수 있어.</p></div><button className="primary" onClick={()=>setPersonaEditor({name:'',description:''})}><Plus size={18}/> 페르소나 추가</button></header><div className="character-grid">{personas.map(p=><article className="persona-card" key={p.id}><div className="avatar small">{p.name.slice(0,1)}</div><h2>{p.name}</h2><p>{p.description}</p><div className="row"><button className="text-button" onClick={()=>setPersonaEditor(p)}>수정</button><button className="text-button danger" onClick={async()=>{if(!confirm('이 페르소나를 삭제할까?'))return;await db.from('rp_personas').delete().eq('id',p.id);load()}}>삭제</button></div></article>)}{!personas.length&&<div className="empty">페르소나를 만들면 채팅 설정에서 선택할 수 있어.</div>}</div></>}
 {view==='usage'&&<><header className="page-head"><div><span className="eyebrow">API USAGE</span><h1>사용 비용</h1><p>Gemini API의 토큰 기준 예상 비용이야. 실제 청구액은 Google에서 확인해 줘.</p></div></header><div className="stats"><div><small>{month} 이번 달</small><strong>{money(monthCost)}</strong><span>{monthly.length}번의 호출</span></div><div><small>전체 누적</small><strong>{money(usages.reduce((a,u)=>a+Number(u.cost_usd),0))}</strong><span>대화 및 요약 포함</span></div></div><h2 className="usage-title">캐릭터별 사용량</h2><div className="usage-list">{characters.map(c=><div key={c.id}><span>{c.name}</span><b>{money(characterCost(c.id))}</b></div>)}</div><h2 className="usage-title">이번 달 모델별</h2><div className="usage-list">{[...new Set(monthly.map(u=>u.model))].map(m=><div key={m}><span>{m}</span><b>{money(monthly.filter(u=>u.model===m).reduce((a,u)=>a+Number(u.cost_usd),0))}</b></div>)}</div></>}
 {view==='chat'&&session&&<div className="chat-shell"><header className="chat-head"><button className="icon" onClick={()=>{setView('detail');setDrawer(null)}}><ArrowLeft/></button><div className="chat-avatar">{character?.name.slice(0,1)}</div><div className="grow"><b>{character?.name}</b><small>{session.title}</small></div><button className="icon" title="대화 목록" onClick={()=>setDrawer(drawer==='history'?null:'history')}><Menu size={20}/></button><button className="icon" title="기억" onClick={()=>setDrawer(drawer==='memory'?null:'memory')}><Brain size={20}/></button><button className="icon" title="설정" onClick={()=>setDrawer(drawer==='settings'?null:'settings')}><Settings2 size={20}/></button></header><div className="chat-scroll"><div className="chat-inner">{character?.scenario&&<p className="scene">{character.scenario}</p>}{character?.opening&&<div className="bubble model opening"><span>{character.name}</span><p>{character.opening}</p></div>}{messages.map((m,i)=><div key={m.id} className={'message '+m.role}><div className={'bubble '+m.role}>{m.role==='model'&&<span>{character?.name}</span>}{m.is_ooc&&<small>OOC</small>}<p>{m.content}</p>{m.role==='model'&&m.input_tokens>0&&<small className="token">{m.input_tokens.toLocaleString()} 입력 · {m.output_tokens.toLocaleString()} 출력 · {money(Number(m.cost_usd))}</small>}</div><button className="msg-more" onClick={()=>setMenuId(menuId===m.id?null:m.id)}><MoreHorizontal size={17}/></button>{menuId===m.id&&<div className="pop message-menu"><button onClick={()=>{setMenuId(null);branchAt(i)}}><GitBranch size={15}/> 여기서 분기</button>{m.role==='user'&&<button onClick={()=>{setEditMessage(m);setDraft(m.content);setMenuId(null)}}><Pencil size={15}/> 수정해서 분기</button>}{m.role==='model'&&i===messages.length-1&&<button onClick={()=>{setMenuId(null);respond(true)}}><RefreshCcw size={15}/> 다시 생성</button>}</div>}</div>)}{busy&&<div className="typing"><span/><span/><span/></div>}{error&&<div className="error chat-error">{error}{messages.at(-1)?.role==='user'&&!busy&&<button onClick={()=>respond(true)}>다시 시도</button>}</div>}<div ref={bottom}/></div></div><div className="composer"><div className="composer-box">{editMessage&&<div className="edit-banner">메시지를 수정해 새 분기 만들기 <button onClick={()=>{setEditMessage(null);setDraft('')}}><X size={16}/></button></div>}<textarea value={draft} rows={1} placeholder="이야기를 이어가…  /ooc 로 역할극 밖에서 말하기" onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();if(editMessage)branchAt(messages.findIndex(m=>m.id===editMessage.id),draft);else respond()}}}/><div className="compose-foot"><span>{session.model} · 누적 {money(sessionCost)}</span><button className="send" disabled={busy||!draft.trim()} onClick={()=>editMessage?branchAt(messages.findIndex(m=>m.id===editMessage.id),draft):respond()}><Send size={18}/></button></div></div></div>
 {drawer&&<div className="drawer-back" onClick={()=>setDrawer(null)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><h2>{drawer==='settings'?'대화 설정':drawer==='memory'?'기억 관리':'이전 이야기'}</h2><button className="icon" onClick={()=>setDrawer(null)}><X/></button></div>{drawer==='settings'&&<div className="drawer-body"><label>채팅 이름<input value={session.title} onChange={e=>setSession({...session,title:e.target.value})} onBlur={()=>changeSession({title:session.title})}/></label><label>모델<select value={session.model} onChange={e=>changeSession({model:e.target.value})}>{models.map(m=><option key={m}>{m}</option>)}</select></label><label>Thinking<select value={session.thinking} onChange={e=>changeSession({thinking:e.target.value})}><option value="low">낮음 · 빠르고 절약</option><option value="medium">보통</option><option value="high">높음 · 깊은 추론</option></select></label><label>답변 길이<select value={session.length} onChange={e=>changeSession({length:e.target.value})}><option value="short">짧게</option><option value="normal">보통</option><option value="long">길게</option></select></label><label>내 페르소나<select value={session.persona_id||''} onChange={e=>changeSession({persona_id:e.target.value||null})}><option value="">지정 안 함</option>{personas.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="drawer-stat"><span>이 대화 비용</span><b>{money(sessionCost)}</b></div><div className="drawer-stat"><span>자동 요약</span><small>{session.summary||'아직 요약할 오래된 대화가 없어.'}</small></div><button className="outline danger" onClick={()=>deleteSession(session)}><Trash2 size={17}/> 대화 삭제</button></div>}{drawer==='memory'&&<div className="drawer-body"><p className="hint">중요한 설정이나 사건을 직접 고정해 둬. 자동 요약은 대화가 길어지면 갱신돼.</p>{memories.map(m=><div className="memory-item" key={m.id}><p>{m.content}</p><button onClick={()=>{setMemoryDraft(m.content);setMemoryEditId(m.id)}}><Pencil size={14}/></button><button className="danger" onClick={()=>removeMemory(m.id)}><Trash2 size={14}/></button></div>)}<textarea rows={3} placeholder="잊지 않았으면 하는 사실" value={memoryDraft} onChange={e=>setMemoryDraft(e.target.value)}/><button className="primary" onClick={saveMemory}><Plus size={17}/>{memoryEditId?'기억 수정':'기억 추가'}</button></div>}{drawer==='history'&&<div className="drawer-body"><button className="primary" onClick={()=>character&&createSession(character)}><Plus size={17}/> 새 채팅</button>{selectedSessions.map(s=><button className={'history-row '+(s.id===session.id?'selected':'')} key={s.id} onClick={()=>openSession(s)}>{s.title}<small>{new Date(s.updated_at).toLocaleDateString('ko-KR')}</small></button>)}</div>}</aside></div>}</div>}
 </main><nav className="mobile-nav"><button onClick={()=>setView('library')}><BookOpen size={20}/>캐릭터</button><button onClick={()=>setView('personas')}><UserRound size={20}/>페르소나</button><button onClick={()=>setView('usage')}><ChartNoAxesColumn size={20}/>비용</button></nav>
 {editor&&<div className="modal-back" onClick={()=>setEditor(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">CHARACTER DESIGN</span><h2>{editor.id?'캐릭터 설정 수정':'새 캐릭터 만들기'}</h2></div><button className="icon" onClick={()=>setEditor(null)}><X/></button></div><div className="form-scroll">{(Object.keys(labels) as (keyof typeof blankCharacter)[]).map(k=><label key={k}>{labels[k]}{k==='name'||k==='description'?<input value={editor[k]||''} onChange={e=>setEditor({...editor,[k]:e.target.value})} placeholder={k==='name'?'이름을 입력해':'짧게 소개해 줘'}/>:<textarea rows={k==='world'||k==='secrets'?4:3} value={editor[k]||''} onChange={e=>setEditor({...editor,[k]:e.target.value})} placeholder={`${labels[k]}을 적어 줘`}/>}</label>)}</div><div className="modal-foot"><button className="outline" onClick={()=>setEditor(null)}>취소</button><button className="primary" onClick={saveCharacter} disabled={busy}><Save size={17}/> 저장</button></div></div></div>}
 {personaEditor&&<div className="modal-back" onClick={()=>setPersonaEditor(null)}><div className="modal small-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><h2>내 페르소나</h2><button className="icon" onClick={()=>setPersonaEditor(null)}><X/></button></div><div className="form-scroll"><label>이름<input value={personaEditor.name||''} onChange={e=>setPersonaEditor({...personaEditor,name:e.target.value})}/></label><label>설정<textarea rows={7} value={personaEditor.description||''} onChange={e=>setPersonaEditor({...personaEditor,description:e.target.value})}/></label></div><div className="modal-foot"><button className="primary" onClick={savePersona}>저장</button></div></div></div>}
 </div>
}
